# Generated by Django 5.1.2 on 2025-04-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_employee_email_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='last_number',
            new_name='last_name',
        ),
    ]
