# Generated by Django 5.1.2 on 2025-04-10 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0008_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('injury', 'Personal Injury'), ('equipment', 'Equipment Failure'), ('spill', 'Chemical Spill'), ('near_miss', 'Near Miss'), ('security', 'Security Breach')], max_length=50)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_taken', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.productionline')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.employee')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('bottle_seal', 'Bottle Seal Integrity'), ('fill_level', 'Fill Level'), ('label_placement', 'Label Placement'), ('sugar_content', 'Sugar Content'), ('carbonation', 'Carbonation Level'), ('packaging', 'Packaging Quality')], max_length=50)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_check_due', models.DateTimeField()),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.employee')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.productionline')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_areas', models.ManyToManyField(to='mywebsite.productionline')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.department')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.safetychecklist')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_critical', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mywebsite.safetychecklist')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('training_type', models.CharField(choices=[('safety', 'Safety Training'), ('quality', 'Quality Control'), ('equipment', 'Equipment Operation'), ('hygiene', 'Hygiene Practices'), ('soft_skills', 'Soft Skills')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField(help_text='Duration in hours')),
                ('location', models.CharField(max_length=100)),
                ('max_participants', models.PositiveIntegerField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_groups', models.ManyToManyField(help_text='Which departments should attend', to='mywebsite.department')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_conducted', to='mywebsite.employee')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('cola_330ml', 'Coca-Cola 330ml'), ('cola_500ml', 'Coca-Cola 500ml'), ('cola_1l', 'Coca-Cola 1L'), ('sprite_330ml', 'Sprite 330ml'), ('fanta_500ml', 'Fanta Orange 500ml'), ('schweppes_1l', 'Schweppes 1L')], max_length=50)),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift (8AM-4PM)'), ('afternoon', 'Afternoon Shift (12PM-8PM)'), ('night', 'Night Shift (8PM-4AM)')], max_length=20)),
                ('target_quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.productionline')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.department')),
            ],
            options={
                'ordering': ['date', 'shift'],
                'unique_together': {('product', 'production_line', 'shift', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_registrations', to='mywebsite.employee')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='mywebsite.trainingsession')),
            ],
            options={
                'unique_together': {('training', 'employee')},
            },
        ),
    ]
