# Generated by Django 5.1.2 on 2025-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0009_incidentreport_qualitycheck_safetyalert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-year', '-month', 'employee__user__last_name']},
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'year', 'month')},
        ),
    ]
