# Generated by Django 5.1.2 on 2025-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0011_alter_payroll_allowances_alter_payroll_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='allowances',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deductions',
            field=models.JSONField(default=dict),
        ),
    ]
