# Generated by Django 5.1.2 on 2025-04-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0013_alter_payroll_allowances_alter_payroll_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryvehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_vehicles/'),
        ),
    ]
