# Generated by Django 5.1.2 on 2025-04-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0016_statuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mywebsite.deliveryvehicle'),
            preserve_default=False,
        ),
    ]
