# Generated by Django 5.1.2 on 2025-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0017_delivery_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('van', 'Van'), ('truck', 'Truck'), ('pickup', 'Pickup'), ('bike', 'Bike'), ('trailer', 'Trailer')], max_length=50, null=True),
        ),
    ]
