# Generated by Django 5.1.2 on 2025-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0018_alter_deliveryvehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryvehicle',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryvehicle',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
