# Generated by Django 5.1.2 on 2025-04-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0019_deliveryvehicle_model_deliveryvehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('ceo', 'Chief Executive Officer'), ('coo', 'Chief Operating Officer'), ('cfo', 'Chief Financial Officer'), ('cto', 'Chief Technology Officer'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('developer', 'Software Developer'), ('analyst', 'Business Analyst'), ('qa_analyst', 'Quality Assurance Analyst'), ('hr', 'Human Resources'), ('recruiter', 'Recruiter'), ('payroll_specialist', 'Payroll Specialist'), ('marketing', 'Marketing Specialist'), ('brand_manager', 'Brand Manager'), ('sales', 'Sales Executive'), ('account_manager', 'Account Manager'), ('engineer', 'Manufacturing Engineer'), ('maintenance_tech', 'Maintenance Technician'), ('logistics', 'Logistics Coordinator'), ('warehouse', 'Warehouse Operator'), ('forklift_operator', 'Forklift Operator'), ('supply_chain', 'Supply Chain Manager'), ('procurement', 'Procurement Officer'), ('legal', 'Legal Counsel'), ('support', 'IT Support'), ('it_admin', 'IT Administrator'), ('data_scientist', 'Data Scientist'), ('driver', 'Delivery Driver'), ('security', 'Security Officer'), ('cleaner', 'Cleaner'), ('intern', 'Intern'), ('consultant', 'Consultant'), ('admin', 'Administrative Assistant')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FacilityChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_fields', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='mywebsite.productionfacility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
