# Generated by Django 5.1.2 on 2025-04-12 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0020_alter_employee_position_facilitychangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('started', 'Work Started'), ('completed', 'Work Completed'), ('cancelled', 'Cancelled'), ('updated', 'Updated'), ('part_replaced', 'Part Replaced'), ('note_added', 'Note Added')], max_length=20, verbose_name='Action Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('parts_used', models.JSONField(blank=True, help_text='JSON of parts and quantities used', null=True, verbose_name='Parts Inventory Used')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mywebsite.maintenanceschedule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Maintenance Log Entry',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['maintenance'], name='mywebsite_m_mainten_f9ce88_idx'), models.Index(fields=['action'], name='mywebsite_m_action_bf1589_idx'), models.Index(fields=['timestamp'], name='mywebsite_m_timesta_eef895_idx')],
            },
        ),
    ]
