# Generated by Django 5.1.2 on 2025-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0021_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
