# Generated by Django 5.1.2 on 2025-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0022_maintenanceschedule_actual_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Work Description'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
