# Generated by Django 5.1.2 on 2025-04-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0023_maintenanceschedule_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
