# Generated by Django 5.1.2 on 2025-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0024_supplier_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
