# Generated by Django 5.1.2 on 2025-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0025_supplier_contract_end_supplier_contract_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='products_services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
