# Generated by Django 5.2 on 2025-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0026_supplier_notes_supplier_products_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='selling_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
