# Generated by Django 5.2 on 2025-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0027_productvariant_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Admin'), ('security', 'Security')], default='employee', max_length=20),
        ),
    ]
