# Generated by Django 5.2 on 2025-05-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0029_visitor_securityguard_securityreport_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
