# Generated by Django 5.2 on 2025-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0030_department_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Shift (6AM-2PM)'), ('afternoon', 'Afternoon Shift (2PM-10PM)'), ('night', 'Night Shift (10PM-6AM)')], max_length=50, null=True),
        ),
    ]
