# Generated by Django 5.2 on 2025-05-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0031_securityguard_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
