# Generated by Django 5.2 on 2025-05-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0033_incidentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(choices=[('production', 'Production Area'), ('warehouse', 'Warehouse'), ('office', 'Office Area'), ('parking', 'Parking Lot'), ('perimeter', 'Perimeter'), ('gate', 'Gate'), ('other', 'Other')], max_length=50)),
                ('is_high_risk', models.BooleanField(default=False)),
            ],
        ),
    ]
