# Generated by Django 5.2 on 2025-05-13 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0034_incidentlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reported_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='reported', max_length=50)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], max_length=20)),
                ('witnesses', models.TextField(blank=True, null=True)),
                ('immediate_actions_taken', models.TextField()),
                ('potential_impact', models.TextField(blank=True, null=True)),
                ('requires_management_notification', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('is_safety_related', models.BooleanField(default=False)),
                ('is_security_related', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='mywebsite.securityguard')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mywebsite.incidentcategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mywebsite.incidentlocation')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to='mywebsite.securityguard')),
            ],
        ),
    ]
