# Generated by Django 5.2 on 2025-05-13 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0036_incidentfollowup_incidentmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_person', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('in_person', 'In Person'), ('message', 'Text Message')], max_length=50)),
                ('notification_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_received', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mywebsite.securityincidentreport')),
            ],
        ),
    ]
