# Generated by Django 5.2 on 2025-05-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0037_managementnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('morning', 'Morning Shift (6AM-6PM)'), ('afternoon', 'Afternoon Shift (2PM-10PM)'), ('night', 'Night Shift (6PM-6AM)')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('handover_notes', models.TextField(blank=True)),
                ('equipment_handover', models.TextField(blank=True)),
                ('supervisor_comments', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mywebsite.securityguard')),
                ('incidents_during_shift', models.ManyToManyField(blank=True, to='mywebsite.incidentreport')),
            ],
        ),
    ]
