# Generated by Django 5.2 on 2025-05-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0038_securityshiftlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('entrance', 'Main Entrance'), ('parking', 'Parking Lot'), ('warehouse', 'Warehouse'), ('office', 'Office Area'), ('production', 'Production Floor')], max_length=50)),
                ('ip_address', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('installation_date', models.DateField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CCTVRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('file_path', models.CharField(max_length=255)),
                ('incident_reported', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('cctv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='mywebsite.cctv')),
            ],
        ),
    ]
