# Generated by Django 5.2 on 2025-05-13 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0040_door_biometricdata_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PASystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_maintenance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PAAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_line1', models.CharField(max_length=100)),
                ('message_line2', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast_at', models.DateTimeField(blank=True, null=True)),
                ('is_broadcast', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.pasystem')),
            ],
        ),
    ]
