# Generated by Django 5.2 on 2025-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0042_itemtype_item_itemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='visits', to='mywebsite.item'),
        ),
    ]
