# Generated by Django 5.2 on 2025-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0043_visitlog_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='batch_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
